### ISSUE TITLE
Support 'byte' datatype in ncml

### ISSUE THREAD

**Issue by heikoklein** [metno/fimex#14]
For compatiblity with unidata's ncml it might be an advantage to implement the 'byte' datatype for ncml-files: https://www.unidata.ucar.edu/software/netcdf-java/current/ncml/AnnotatedSchema4.html#DataType

byte could internally just fallback to char.

byte makes the intend of the datatype-usage (very short integer) much clearer than char.

**Comment by alexander-buerger-met-no** [comment]
> Unsigned integer types (byte, short, int) are indicated with an _Unsigned = "true" attribute on the Variable.

And from the [FAQ](https://www.unidata.ucar.edu/software/netcdf-java/v4.5/reference/faq.html#ncml_unsigned): `<attribute name="_Unsigned" value="true" />`

This is also quite different between fimex ncml and standard ncml. Fimex wants, e.g.,  `uint` and does not interpret the `_Unsigned` attribute.

**Comment by heikoklein** [comment]
Agreed that there are more incompatibilities between unidata and fimex ncml, in particularly concerning netcdf4. So, yes, supporting the _Unsigned might be a good idea, too.

**Comment by alexander-buerger-met-no** [comment]
Done with commit 135545a2.
