### ISSUE TITLE
Missing pkg_config for fortran libfimexf

### ISSUE THREAD

**Issue by heikoklein** [metno/fimex#16]
Hi,
I'm using the fortran module of fimex in https://github.com/metno/snap . It works well, but building requires manually setting the fimex-fortran library. The c-library works nicely with pkg-config, but I need to add the fortran library manually, i.e.
```
INC=`pkg-config --cflags fimex`
LIBS=`pkg-config --libs fimex` -lfimexf-1.4
```

It would be nice to have the a pkg-config file for fimexf, in particularly for the versionized libraries.

**Comment by alexander-buerger-met-no** [comment]
Should be solved with commit f046fcf4.
