### ISSUE TITLE
Support ecCodes rather than the deprecated gribApi

### ISSUE THREAD

**Issue by heikoklein** [metno/fimex#3]
EC has announced end of life for GRIB-API at the end of 2018, and will replace it with ecCodes.

Fimex needs compilation/configure support for ecCodes, and should follow the migration guideline: https://software.ecmwf.int/wiki/display/ECC/GRIB-API+migration In particular, fimex uses grib_handle_new_from_template for writing.

**Comment by alexander-buerger-met-no** [comment]
This function is no longer used in master, see [commit 3675e7e](https://github.com/metno/fimex/commit/3675e7e283798fb5e1fd886a8cdfed2f3bef014e).

ecCodes compilation support is currently missing.

**Comment by heikoklein** [comment]
Great, my master branch was slightly outdated.

**Comment by alexander-buerger-met-no** [comment]
Version 0.64.0~rc1 supports sompilation with ecCodes.
