### ISSUE TITLE
GribCDMWriter drops fields when all values are missing

### ISSUE THREAD

**Issue by heikoklein** [metno/fimex#32]
The GribCDMWriter drops fields where all data are missing. While this might be a useful strategy for some cases it is not for cases where i.e. sparse fields are written out and compressed using i.e. bitmap-compression.

**Comment by alexander-buerger-met-no** [comment]
Do you have any suggestions on how to address this?

**Comment by heikoklein** [comment]
What about adding processing-options to the cdmGribWriterConfix.xml like
```
<processingOptions omitEmptyFields="false" />
```
I can come up with an example and maybe with a patch.

**Comment by alexander-buerger-met-no** [comment]
Is this something new in fmex 1.8? I do not see any relevant changes between 1.7 and 1.8.

**Comment by alexander-buerger-met-no** [comment]
Closed with commit 0bc10eb5, which is included in fimex 1.8.1.
