### ISSUE TITLE
How to use metgm with 1.9.4?

### ISSUE THREAD

**Issue by TaimoPriinits** [metno/fimex#34]
Hello!

Im trying to convert grib2 to metgm and don't understand how to add METGM_API as a plugin to fimex.
I managed to install fimex-1.8.1 with metgm enable but had to change some arguments of functions to make it happen (didn't quite manage to make conversion work tho) so when I noticed that now fimex uses plugins maybe its better to use this route.

Thanks in advance!

**Comment by alexander-buerger-met-no** [comment]
The MetGM format requires the non-public third-party metgm library. Please confirm that you have obtained and installed this library. After that, we can see how we can help you further with the integration to fimex.

**Comment by TaimoPriinits** [comment]
yes. I Have that library

**Comment by TaimoPriinits** [comment]
bump :)

**Comment by alexander-buerger-met-no** [comment]
Could you send an email to fimex@met.no?

**Comment by TaimoPriinits** [comment]
Seems like I need to subscribe to fimex mailing list before I am allowed to send emails. Waiting for approval...
