### ISSUE TITLE
All fimex operations fail when coordinate-system is unknown

### ISSUE THREAD

**Issue by heikoklein** [metno/fimex#8]
Using the file at https://drive.google.com/open?id=1_bX1sba0gZiYsWYl3J89RlICiQzEL53u a simple 

``` fimex --input.file=omerc_proj_string.nc --input.printNcML ```

fails with a CDMException: unsupported projection: oblique_mercator

All other operations like extraction or writing, which are CoordinateSystem independent, fail too.

I guess the problem lies in fimex.cc always creating a CDMInterpolator object, even if that one is not needed. CDMInterpolator always needs CoordinateSystem information, so that is ok, but it should not be initialized n fimex.cc.

**Comment by alexander-buerger-met-no** [comment]
I cannot reproduce the problem with the given file in fimex 0.66.
Anyhow, with commit 73cf110, fimex only creates a CDMInterpolator object if needed.

**Comment by heikoklein** [comment]
Thanks, can confirm it works after using ncatted to rename the grid_mapping_name. oblique_mercator is now known in newer versions of fimex.
