### ISSUE TITLE
fiGrbmlCat fails to generate correct grbml from multiple inputs

### ISSUE THREAD

**Issue by joewkr** [metno/fimex#9]
Hi,

I'm trying to use `fiGrbmlCat` to merge a few `*.grbml` index files and produce a single GRIB index file. But it seems that `fiGrbmlCat` does not correctly handle such a case and produces a corrupted index file with multiple unbalanced `</gribFileIndex>` tags.

This problem is caused by [fiGrbmlCat.cc#L130](https://github.com/metno/fimex/blob/master/src/binSrc/fiGrbmlCat.cc#L130) of the `grbmlExtract` function, where the end tag is added after processing an input file. This function is called in a loop for each input, thus producing multiple `</gribFileIndex>`.

**Comment by alexander-buerger-met-no** [comment]
Thanks. Closed with commit 065aa664.
